---
title: "Updated Jello-Shot Analysis April 2022"
author: "Jeff Brabec"
date: "4/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(lubridate)
library(readxl)
library(future)
library(furrr)
library(doParallel)

#Load custom functions
fun.dir <- list.files(here("src"), full.names = TRUE)
for(i in 1:length(fun.dir)){source(fun.dir[i])}
```

# Calibration Slopes
```{r}
calibration_vals <- read_xlsx(here("data/Compiled Calibrations.xlsx"))
```

# Read in and process data
```{r message=FALSE}

jello_pred_data <- get_jello_consumption(dir = here("data/recordings"), 
                                         calibrations = calibration_vals,
                                         results_dir = here("results/march_preds"))

april_pred_data <- get_jello_consumption(dir = here("data/4-2022"),
                                         calibrations = calibration_vals,
                                         results_dir = here("results/april_preds"))

may_pred_data <- get_jello_consumption(dir = here("data/5-2022"),
                                       calibrations = calibration_vals,
                                       results_dir = here("results/may_preds"))
```

# Bin and Convert
```{r}

get_binned_data(dir = here("results/april_preds"),
                bin = "30 mins", 
                time_increment = "time_m",
                results_dir = here("results/april_30_bins"))

get_binned_data(dir = here("results/may_preds"),
                bin = "30 mins", 
                time_increment = "time_m",
                results_dir = here("results/may_30_bins"))

get_binned_data(dir = here("results/pred_readings"),
                bin = "60 mins", 
                time_increment = "time_h",
                results_dir = here("results/hour_bins"))
```

